name = "etch-kaplas"
license = "UNLICENSED"
licenselink = "https://github.com/kaplas/homepage-hugo/blob/master/LICENSE"
description = "Lightweight Hugo theme with a focus on content"
homepage = "https://github.com/kaplas/homepage-hugo"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41"

[author]
  name = "Jouni Kaplas"
  homepage = "https://www.kaplas.net"
